package.json, src/stories/designPrinciples.stories.mdx, src/stories/spacing.stories.tsx, src/theme/theme.ts
=> Modifies spacing to improve compatibility.

src/util/copy.tsx
=> Do not log the clipboard text

stories/spacing.stories.tsx, stories/theme/theme.stories.tsx
=> Change to newer 6.0 story configuration

package.json, src/theme/darkTheme.ts, test/theme/__snapshots__/createTheme.test.ts.snap
`black` causes an issue with MUI DataTable.
=> Change dark theme default background to hex

.storybook/components/DocContainer.tsx, .storybook/preview.js
https://github.com/hipstersmoothie/storybook-dark-mode/issues/127
=> Fixes the storybook docs styling

package-lock.json, package.json, src/components/Icons/Check.tsx, src/components/Icons/CheckIndeterminate.tsx, src/components/Icons/ChevronDown.tsx, src/components/Icons/Close.tsx, src/components/Icons/Icons.stories.tsx, src/components/Icons/Icons.tsx, src/components/Icons/index.ts, src/components/Svg/Svg.tsx, src/utils/stitches.config.ts
Has this as a direct dependency but could be changed to a peer dependency.
see #81
=> Adds method for using @mdi/js Icons

src/components/Card/Card.stories.tsx, src/components/Card/Card.test.tsx, src/components/Card/Card.tsx, src/components/IconButton/IconButton.stories.tsx, src/components/IconButton/IconButton.tsx, src/utils/stitches.config.ts
Also updates IconButton - it may as well take the path directly for
the most common use case.
Fixes #110
=> Updates card with subcomponents

src/components/Button/Button.tsx, src/components/Chip/Chip.tsx, src/docs/util/Variants.tsx
fit-content is not supported on firefox without the modifier.
Fixes #118
=> Fixes for button and chip on firefox

src/components/Input/Input.stories.tsx, src/components/Input/Input.test.tsx, src/components/Input/Input.tsx
The onChange should be passed through by the polymorphic but it
is not at the moment, so adding explicitly.
Also added onValueChange to match the api elsewhere.
fixes #129
=> Add onChange and onValueChange to Input

.storybook/preview.js, jest.patch-cssom.js, package-lock.json, package.json, src/components/ThemeProvider/ThemeProvider.tsx, src/utils/stitches.config.ts
Requires patch for cssom for tests to run properly.
Updates theme setup.
fixes #136
=> Update stitches version to 0.2.0

src/components/AppBar/AppBar.tsx
Simplifies layout and fixes item alignment.
incorporates #140 fix, slightly different due to simplification.
fixes #129
=> Fixes app AppBarMenu layout

src/components/Button/Button.tsx, src/components/IconButton/IconButton.tsx
Made Primary disabled button looks more disabled
Fixes #149
Before:
After:
=> Better differentiate disabled buttons

package-lock.json, package.json
Will do another release once merged.
=> update to stitches0.2.2

package-lock.json, package.json, sonar-project.properties, src/docs/introduction.stories.mdx
fixes issue with intro page on storybook
corrects sonar exclusion
fixes #166
=> Updates to typescript 4.3

.storybook/committed/theme.js, src/components/ThemeProvider/ThemeController.tsx, src/components/ThemeProvider/ThemeProvider.stories.tsx, src/components/ThemeProvider/ThemeProvider.test.tsx, src/components/ThemeProvider/ThemeProvider.tsx, src/stitches.config.ts
This should alow theme values to be used in committed-graph
fixes #174
=> Adds useTheme hook

src/components/ThemeProvider/ThemeProvider.stories.tsx, src/components/ThemeProvider/ThemeProvider.tsx, src/stitches.config.ts
We create light and dark fully populated theme objects for use
outside of stitiches. This is done minimally, so there is not more work
done by stitches.
They can then be accessed from useTheme.
See #174
=> Further improvements to the theme handling

src/stitches.config.ts
=> Adds background colour to global body styles

package.json, src/components/Dialog/Dialog.stories.tsx, src/components/Dialog/Dialog.tsx
=> Changes dialog close to use slot 

.github/workflows/release.yml
Merge error caused two names to be in the file, one removed
**What is the purpose of this pull request? (put an "X" next to item)**
[ ] Bug fix
[ ] Enhancement
[ ] Documentation
[ ] Deployment
[ ] Process (e.g. improve continuous integration)
[ ] Other, please explain:
**Which issue (if any) does this pull request address?**
Fixes
**What changes did you make?**
**Is there anything you'd like reviewers to focus on?**
=> fix(ci): fixes release script

.github/workflows/release.yml
Move the sonar to the end so test artefacts will exist.
=> ci: Fixes error in CI process

package-lock.json, package.json, src/components/Accordion/Accordion.test.tsx, src/components/Button/Button.test.tsx
Updates typescript to latest release
Adds storybook-testing and a couple of tests to try it out
=> test: add storybook-testing

src/components/ConfirmDialog/ConfirmDialog.tsx, src/components/Dialog/Dialog.tsx, src/components/Drawer/Drawer.tsx, src/components/Menu/Menu.tsx, src/components/Popover/Popover.stories.tsx, src/components/Popover/Popover.tsx, src/components/ThemeProvider/ThemeController.tsx, src/utils/test-utils.tsx
Removes the `asChild` prop where already set in the component.
Adds window listeners to make theme change if the user changes the system preference for light/dark theme.
=> Minor fix and new feature in themes

package.json, src/components/Select/Select.stories.tsx
Adds host 0.0.0.0 to storybook
See  #230
=> docs: adds story to test Dialog and Select issue

package.json, src/components/Select/Select.stories.tsx, src/components/Select/Select.tsx, src/docs/examples/form.stories.tsx
**What is the purpose of this pull request? (put an "X" next to item)**
[ ] Bug fix
[ x ] Enhancement
[ ] Documentation
[ ] Deployment
[ ] Process (e.g. improve continuous integration)
[ ] Other, please explain:
**Which issue (if any) does this pull request address?**
Fixes #238
=> Updates Select component to be based on Radix Select

.github/workflows/ci.yml, src/components/FormControl/FormControl.tsx, src/components/Input/Input.tsx
FormControl and Input fixes
see #264, #265, #267
=> Minor fixes found in using version 7

package-lock.json, package.json, src/components/IconButton/IconButton.tsx, src/components/Icons/Icons.tsx, src/components/Toggle/Toggle.stories.tsx, src/components/Toggle/Toggle.tsx, src/components/Toggle/Toogle.test.tsx, src/components/Toggle/index.ts, src/components/ToggleGroup/ToggleGroup.stories.tsx, src/components/ToggleGroup/ToggleGroup.tsx, src/components/ToggleGroup/ToogleGroup.test.tsx, src/components/ToggleGroup/index.ts
**What is the purpose of this pull request? (put an "X" next to item)**
[ ] Bug fix
[ x ] Enhancement
[ ] Documentation
[ ] Deployment
[ ] Process (e.g. improve continuous integration)
[ ] Other, please explain:
**Which issue (if any) does this pull request address?**
Fixes #202
Issues/TODOs: 
[ ] Hover isn't applying properly during pressed state
[ ] Toggle group orientation isn't working as intended (This might be a Radix issue as it also doesn't seem to working in [their code sandbox example](https://codesandbox.io/s/spring-frog-5ny1ym?file=/App.js))
=> feat: adds toggle and toggle group components

src/docs/colours.stories.mdx
Changes to use the components provider.
=> fix: fix for colour page in storybook

package-lock.json, package.json, src/typings.d.ts
Updates ts to max currently supported version. There are issues updating to 4.8.
See:
https://github.com/stitchesjs/stitches/issues/1078
https://github.com/stitchesjs/stitches/pull/1082
=> fix: update ts and stitches version
